### ISSUE TITLE
Errors caused (probably) by outdated dependencies

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [xvik/gradle-mkdocs-plugin#29]
I am seeing some errors in all my repos.

https://github.com/JavierSegoviaCordoba/mokoki/runs/5724095725?check_suite_focus=true

https://github.com/JavierSegoviaCordoba/either/runs/5724093619?check_suite_focus=true

**Comment by JavierSegoviaCordoba** [comment]
I have checked `pipUpdates` but I am not running the plugin locally, I run it only on CI, is there any task that just updates everything before running building the docs?

**Comment by xvik** [comment]
The cause: https://github.com/mkdocs/mkdocs/issues/2799

Version ranges are pure evil! :) 

The best way to workaround now it to specify jinja version (should work):

```
python.pip 'jinja2:3.0.0'
```

The other option is to update mkdocs (to teh fixed version):

```
python.pip 'mkdocs:1.3.0', 'mkdocs-material:8.2.8'
```

I havn't looked yet what was changed in the latest versions and can't tell if it works out of the box, but in any case you will not face any issues related to gradle plugin itself.

I will update the plugin soon (in a couple of days).

**Comment by mattinger** [comment]
You might want to consider making the version of mkdocs configurable by the way via the MkDocsExtension

**Comment by xvik** [comment]
As you can see above, It is already configurable. And even [described in docs](https://xvik.github.io/gradle-mkdocs-plugin/latest/guide/pip/).
By default, plugin configures the following packages:

```
mkdocs:1.2.3
mkdocs-material:8.0.2
pygments:2.10.0
pymdown-extensions:9.1
```

And in some cases you'll need to update all of them to update mkdocs. That's why I don't want to do "easy to use" version configuration - it would be too easy to break everything. So it is intentionlly not very easy to change versions (basic pip packages understanding required).

If you have good arguments for version configuration, I'm always listening (I may be wrong or may not be aware of specific use cases).

**Comment by xvik** [comment]
2.3.0 [released](https://github.com/xvik/gradle-mkdocs-plugin/releases/tag/2.3.0)
