### ISSUE TITLE
Java comment scaner

### ISSUE THREAD

**Issue by ajh123** [xvik/gradle-mkdocs-plugin#37]
Maybe have a feature, where one can use this tool to read all the comments in the Java source and generate markdown files from that. 
It could be complicated, maybe have a look at Sphinx, which does something similar, but it reads Python comments and completely replaces mkdocs. 
Currently I have to use boring JavaDocs when the rest of my site uses the Material theme.

**Comment by xvik** [comment]
Javadoc is a context-orineted help: targeting current method, field, class or package. It is hard to generate a good user documentation using javadoc. There were many attempts for using mkdocs or asciidoc in javadoc (using doclets), but non of these were useful.
Javadoc and user guides are very often completely different in structure and language.

And the second pont is that this plugin is just an integration of mkdocs into gradle ecosystem and enhancement like this is out of scope. 

So would never be done (at least, by me).

**Comment by ajh123** [comment]
Thank you! I can try to make a system myself and post it here

**Comment by xvik** [comment]
Maybe, it would be enought to write a [custom css style](https://www.reddit.com/r/java/comments/2yg6xr/is_there_a_better_looking_javadoc/) to improve your javadoc.

I don't publish generated javadocs (as part of user site) because javadocs are much more useful when generated from sources by IDE. Not sure if anyone is still looking generated javadocs.
